### PR TITLE
chore(deps): bump alloy + revm

### PR DESCRIPTION
**Pull request by 0xDmtri**
Updated revm and alloy as most of the rust ethereum crates already migrated to alloy 0.3.

Removed minor versions of deps in Cargo.toml.

Please let me know if I should change anything.

All tests passed.

### CODE REVIEW

**Comment by 0xDmtri** [comment]
Ah some git jobs failed, looking into it

**Comment by 0xDmtri** [comment]
Hey @DaniPopes 

Could you provide some guidance on implementing [EIP-7702](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7702.md)?

I assume this will need to be done eventually, and I've made some progress so far. However, I want to avoid doing unnecessary work, so I wanted to check if this pull request is relevant to the project.

**Review by DaniPopes — APPROVED** [review]
Pushed EIP-7702 fixes.
Thanks!

**Comment by 0xDmtri** [comment]
> Pushed EIP-7702 fixes. Thanks!

Oh nice! Had a look and it makes sense now, I should've figured it out, still learning the repo :( 

Thanks ser!

**Pull request merged**
